# Metadata
name: ViVi Wiki
description: Official wiki for ViVi
repository: https://github.com/ViVi-Game/ViVi-Wiki

# Structure
source: .
destination: ./_site
collections_dir: .
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes

# Handling Reading
safe: true
disable_disk_cache: true
ignore_theme_config: true
encoding: "utf-8"
strict_front_matter: true

# Filtering Content
show_drafts: false
limit_posts: 0
future: true
unpublished: false

# Conversion
lsi: false
incremental: false
timezone: America/Chicago

# Serving
force_polling: false

# Outputting
profile: false
quiet: false
verbose: false

# SASS
sass:
  sass_dir: _sass
  style: compressed